/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Mon Sep  8 01:01:55 EDT 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkHello.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkHello::MODEL_mkHello()
{
  mkHello_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkHello()
{
  MODEL_mkHello *model = new MODEL_mkHello();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkHello &INST_top = *((MOD_mkHello *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_say_hello;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_say_hello;
	 DEF_INST_top_DEF_CAN_FIRE_RL_say_hello = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_say_hello = DEF_INST_top_DEF_CAN_FIRE_RL_say_hello;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_say_hello)
	   INST_top.RL_say_hello();
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkHello::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkHello_instance = new MOD_mkHello(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkHello_instance->set_clk_0)("CLK");
}
void MODEL_mkHello::destroy_model()
{
  delete mkHello_instance;
  mkHello_instance = NULL;
}
void MODEL_mkHello::reset_model(bool asserted)
{
  (mkHello_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkHello::get_instance()
{
  return mkHello_instance;
}

/* Fill in version numbers */
void MODEL_mkHello::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkHello::get_creation_time()
{
  
  /* Mon Sep  8 05:01:55 UTC 2025 */
  return 1757307715llu;
}

/* State dumping function */
void MODEL_mkHello::dump_state()
{
  (mkHello_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkHello & mkHello_backing(tSimStateHdl simHdl)
{
  static MOD_mkHello *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkHello(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkHello::dump_VCD_defs()
{
  (mkHello_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkHello::dump_VCD(tVCDDumpType dt)
{
  (mkHello_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkHello_backing(sim_hdl));
}
