/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Tue Sep  9 13:45:04 IST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkAdderProviso.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkAdderProviso::MODEL_mkAdderProviso()
{
  mkAdderProviso_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkAdderProviso()
{
  MODEL_mkAdderProviso *model = new MODEL_mkAdderProviso();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkAdderProviso &INST_top = *((MOD_mkAdderProviso *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_test;
	 DEF_INST_top_DEF_CAN_FIRE_RL_test = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_test = DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_test)
	   INST_top.RL_test();
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkAdderProviso::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkAdderProviso_instance = new MOD_mkAdderProviso(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkAdderProviso_instance->set_clk_0)("CLK");
}
void MODEL_mkAdderProviso::destroy_model()
{
  delete mkAdderProviso_instance;
  mkAdderProviso_instance = NULL;
}
void MODEL_mkAdderProviso::reset_model(bool asserted)
{
  (mkAdderProviso_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkAdderProviso::get_instance()
{
  return mkAdderProviso_instance;
}

/* Fill in version numbers */
void MODEL_mkAdderProviso::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkAdderProviso::get_creation_time()
{
  
  /* Tue Sep  9 08:15:04 UTC 2025 */
  return 1757405704llu;
}

/* State dumping function */
void MODEL_mkAdderProviso::dump_state()
{
  (mkAdderProviso_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkAdderProviso & mkAdderProviso_backing(tSimStateHdl simHdl)
{
  static MOD_mkAdderProviso *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkAdderProviso(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkAdderProviso::dump_VCD_defs()
{
  (mkAdderProviso_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkAdderProviso::dump_VCD(tVCDDumpType dt)
{
  (mkAdderProviso_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkAdderProviso_backing(sim_hdl));
}
