/*
 * Generated by Bluespec Compiler, version 2025.01.1 (build 65e3a87a)
 * 
 * On Tue Sep  9 12:31:10 IST 2025
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkALU.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkALU::MODEL_mkALU()
{
  mkALU_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkALU()
{
  MODEL_mkALU *model = new MODEL_mkALU();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkALU &INST_top = *((MOD_mkALU *)(instance_ptr));
	 tUInt8 DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 tUInt8 DEF_INST_top_DEF_WILL_FIRE_RL_test;
	 DEF_INST_top_DEF_CAN_FIRE_RL_test = (tUInt8)1u;
	 DEF_INST_top_DEF_WILL_FIRE_RL_test = DEF_INST_top_DEF_CAN_FIRE_RL_test;
	 if (DEF_INST_top_DEF_WILL_FIRE_RL_test)
	   INST_top.RL_test();
	 if (do_reset_ticks(simHdl))
	 {
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkALU::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkALU_instance = new MOD_mkALU(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkALU_instance->set_clk_0)("CLK");
}
void MODEL_mkALU::destroy_model()
{
  delete mkALU_instance;
  mkALU_instance = NULL;
}
void MODEL_mkALU::reset_model(bool asserted)
{
  (mkALU_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkALU::get_instance()
{
  return mkALU_instance;
}

/* Fill in version numbers */
void MODEL_mkALU::get_version(char const **name, char const **build)
{
  *name = "2025.01.1";
  *build = "65e3a87a";
}

/* Get the model creation time */
time_t MODEL_mkALU::get_creation_time()
{
  
  /* Tue Sep  9 07:01:10 UTC 2025 */
  return 1757401270llu;
}

/* State dumping function */
void MODEL_mkALU::dump_state()
{
  (mkALU_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkALU & mkALU_backing(tSimStateHdl simHdl)
{
  static MOD_mkALU *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkALU(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkALU::dump_VCD_defs()
{
  (mkALU_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkALU::dump_VCD(tVCDDumpType dt)
{
  (mkALU_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkALU_backing(sim_hdl));
}
